[phases.setup]
nix_pkgs = ["nodejs-22_x", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build"]

[phases.start]
cmd = "yarn start:backend"

[variables]
NODE_ENV = "production"